### PR TITLE
release 0.11.0-dev.2619+bd3e248c7

### PR DESCRIPTION
**Pull request by marler8997**

### CODE REVIEW

**Comment by motiejus** [comment]
Maybe worth mentioning also the libresolv functions:  `res_{,n}{search,query,querydomain}` too.

I will submit a bazel mirror request later today and comment the urls here.

**Comment by motiejus** [comment]
https://github.com/bazelbuild/bazel/issues/18114

**Comment by motiejus** [comment]
All artifacts have been mirrored in perpetuity:

    https://mirror.bazel.build/ziglang.org/builds/zig-windows-x86-0.11.0-dev.2619+bd3e248c7.zip
    https://mirror.bazel.build/ziglang.org/builds/zig-windows-aarch64-0.11.0-dev.2619+bd3e248c7.zip
    https://mirror.bazel.build/ziglang.org/builds/zig-macos-aarch64-0.11.0-dev.2619+bd3e248c7.tar.xz
    https://mirror.bazel.build/ziglang.org/builds/zig-macos-x86_64-0.11.0-dev.2619+bd3e248c7.tar.xz
    https://mirror.bazel.build/ziglang.org/builds/zig-linux-x86_64-0.11.0-dev.2619+bd3e248c7.tar.xz
    https://mirror.bazel.build/ziglang.org/builds/zig-linux-x86-0.11.0-dev.2619+bd3e248c7.tar.xz
    https://mirror.bazel.build/ziglang.org/builds/zig-linux-aarch64-0.11.0-dev.2619+bd3e248c7.tar.xz
    https://mirror.bazel.build/ziglang.org/builds/zig-linux-riscv64-0.11.0-dev.2619+bd3e248c7.tar.xz
    https://mirror.bazel.build/ziglang.org/builds/zig-linux-powerpc64le-0.11.0-dev.2619+bd3e248c7.tar.xz
    https://mirror.bazel.build/ziglang.org/builds/zig-linux-powerpc-0.11.0-dev.2619+bd3e248c7.tar.xz

**Comment by marler8997** [comment]
Looks like we missed https://ziglang.org/builds/zig-windows-x86_64-0.11.0-dev.2619+bd3e248c7.zip ?

**Comment by marler8997** [comment]
Submitted the missing mirrored archive for windows x86_64 here: https://github.com/bazelbuild/bazel/issues/18116

**Pull request merged**
